from __future__ import annotations

from typing import Any, Protocol

from app.core.buildings import HouseInfo


class KeyboardFactory(Protocol):
    def jk_keyboard(self, complex_names: list[str], page: int) -> Any: ...
    def house_keyboard(self, houses: list[HouseInfo], page: int) -> Any: ...
    def entrance_keyboard(self, entrances: int) -> Any: ...
    def category_confirm_keyboard(self) -> Any: ...
    def category_select_keyboard(self) -> Any: ...
    def report_confirm_keyboard(self) -> Any: ...
    def phone_reuse_keyboard(self, phone: str) -> Any: ...
